[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/moysklad/*"
  to = "https://api.moysklad.ru/api/remap/1.2/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer 3df691b112eee7a9e14a124222ff313ed0e7d646"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
