[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/moysklad/*"
  to = "https://api.moysklad.ru/api/remap/1.2/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer 26c3d168f4406b10d12a792b60c0c61a8cc77c56"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
